[package]
name = "allure_test_report_upload_to_influxdb"
version = "0.1.0"
edition = "2021"

[dependencies]
core_allure = { path = "../../core/allure" }

tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
reqwest = { workspace = true }